spring:
  application:
    name: English challenge platform
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:/yml/application-prod.yml
      - classpath:/yml/application-dev.yml
      - classpath:/yml/application-local.yml
      - classpath:/yml/logging/application-log.yml
  profiles:
    group:
      logging: log
    active: local
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        flushMode: MANUAL
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


# Swagger
springdoc:
  swagger-ui:
    path: /api-info  # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.

    groups-order: DESC # path, query, body, response 순으로 출력

    tags-sorter: alpha # 태그를 알파벳 순으로 정렬

    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능

  paths-to-match:
    - /** # swagger-ui에 표시할 api의 엔드포인트 패턴


# JWT
jwt:
  issuer: ${MY_JWT_ISSUER}
  secret: ${MY_JWT_SECRET_KEY}

# MICROSOFT AZURE AI TRANSLATOR
microsoft:
  location: ${TRANSLATOR_TEXT_LOCATION}
  endpoint: ${TRANSLATOR_TEXT_ENDPOINT}
  key: ${TRANSLATOR_TEXT_SUBSCRIPTION_KEY}